# Generated by Django 3.0.5 on 2021-04-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('amount', models.FloatField(blank=True, default='0.00', null=True)),
                ('price', models.FloatField(blank=True, default='0.00', null=True)),
                ('type_of_transaction', models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default=None, max_length=4, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
